services:
  - type: web
    name: discordapi
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: PORT
        value: 10000
      - key: BOOST_EMOJI_1
        sync: false
      - key: BOOST_EMOJI_2
        sync: false
      - key: BOOST_EMOJI_3
        sync: false
      - key: BOOST_EMOJI_4
        sync: false
      - key: BOOST_EMOJI_5
        sync: false
      - key: BOOST_EMOJI_6
        sync: false
      - key: BOOST_EMOJI_7
        sync: false
      - key: BOOST_EMOJI_8
        sync: false
      - key: BOOST_EMOJI_9
        sync: false
      - key: NITRO_EMOJI_1
        sync: false
      - key: NITRO_EMOJI_2
        sync: false
      - key: NITRO_EMOJI_3
        sync: false
      - key: NITRO_EMOJI_4
        sync: false
      - key: NITRO_EMOJI_5
        sync: false
      - key: NITRO_EMOJI_6
        sync: false
      - key: NITRO_EMOJI_7
        sync: false
      - key: NITRO_EMOJI_8
        sync: false
      - key: BADGE_EMOJI_QUEST
        sync: false
      - key: BADGE_EMOJI_ORB
        sync: false
      - key: BADGE_EMOJI_ACTIVE_DEV
        sync: false
      - key: BADGE_EMOJI_EARLY_SUPPORTER
        sync: false
      - key: ARCHIVE_CHANNEL_ID
        sync: false
