services:
  - type: web
    name: discordapi
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: PORT
        value: 10000
